# Start the full local stack on Windows / PowerShell.
#
# Usage (run from the project root, or anywhere - paths are resolved):
#   .\scripts\start.ps1                 # start chain-worker + 4 Java services
#   .\scripts\start.ps1 -NoChain        # only the Java services
#   .\scripts\start.ps1 -ResetDb        # rebuild the demo database (same as -Dcampus.reset-db=true)
#
# Notes:
#   - Logs go to .logs/ (same convention as scripts/start.sh).
#   - The working directory is the project root so data-service finds .runtime.
#   - Secrets (service HMAC keys, TLS password, H2 whole-database encryption password) are
#     generated by scripts/setup.mjs into .runtime/secrets.json and injected here BOTH as
#     environment variables and as -D startup properties. Nothing is hardcoded.
#   - JVM options are written to a temporary @argfile because PowerShell splits
#     unquoted -D... arguments (this is the usual reason "ClassNotFoundException: /encoding=UTF-8"
#     shows up on Windows).
#   - ASCII only: Windows PowerShell 5.1 reads .ps1 files as ANSI unless they carry a UTF-8 BOM.
[CmdletBinding()]
param(
    [switch]$ResetDb,
    [switch]$NoChain,
    [string]$JavaHome = $env:JAVA_HOME
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

if (-not $JavaHome) { $JavaHome = 'D:\JAVA\jdk-jb-17' }
$java = Join-Path $JavaHome 'bin\java.exe'
if (-not (Test-Path $java)) { throw "java not found: $java (pass -JavaHome <JDK17 dir>)" }

$logs = Join-Path $root '.logs'
New-Item -ItemType Directory -Force -Path $logs | Out-Null
$runtime = Join-Path $root '.runtime'

# ------------------------------------------------------------------ secrets
$secretsFile = Join-Path $runtime 'secrets.json'
if (-not (Test-Path $secretsFile)) {
    Write-Host '==> secrets.json not found, running scripts/setup.mjs to generate keys and certificates'
    & node (Join-Path $PSScriptRoot 'setup.mjs')
    if (-not (Test-Path $secretsFile)) { throw "setup.mjs did not create $secretsFile" }
}
$secrets = Get-Content -Path $secretsFile -Raw | ConvertFrom-Json
$secretNames = @(
    'GATEWAY_KEY', 'BUSINESS_KEY', 'DATA_KEY', 'AUDIT_KEY', 'LEDGER_KEY',
    'AUDIT_DATA_KEY', 'TLS_PASSWORD', 'DB_PASSWORD', 'DB_CIPHER_KEY'
)
foreach ($name in $secretNames) {
    $value = $secrets.$name
    if (-not $value) { throw "secret '$name' missing in $secretsFile (run: node scripts/setup.mjs --reset)" }
    # process-scope environment variables: inherited by the services started below
    Set-Item -Path ("Env:" + $name) -Value $value
}
# H2 whole-database encryption uses the two-part password "file-key user-password";
# the single-part DB_PASSWORD from the secrets file must NOT be exported as-is.
$dbPassword = $secrets.DB_CIPHER_KEY + ' ' + $secrets.DB_PASSWORD
Set-Item -Path 'Env:DB_PASSWORD' -Value $dbPassword

$arguments = @(
    '-Dfile.encoding=UTF-8',
    ('-Dcampus.runtime=' + $runtime),
    ('-Djavax.net.ssl.trustStore=' + (Join-Path $runtime 'truststore.p12')),
    ('-Djavax.net.ssl.trustStorePassword=' + $secrets.TLS_PASSWORD)
)
# Inject every secret as a -D startup property as well (the documented deployment contract).
foreach ($name in $secretNames) { $arguments += ('-D' + $name + '=' + $secrets.$name) }
# H2 whole-database encryption uses the two-part password "file-key user-password".
# NOTE: the value contains a SPACE, so it MUST be quoted inside the @argfile - the JVM's
# argfile parser splits on whitespace, and an unquoted two-part password becomes two
# arguments (the second one is then read as the main class -> ClassNotFoundException).
$arguments += ('"-DDB_PASSWORD=' + $dbPassword + '"')
if ($ResetDb) { $arguments += '-Dcampus.reset-db=true' }
$argFile = Join-Path $logs 'jvm.args'
Set-Content -Path $argFile -Value $arguments -Encoding ASCII

# Services are started detached (their own hidden shell), so this script can exit while they
# keep running. Redirecting a Start-Process stream keeps the parent alive waiting on the pipe,
# which is why the script would otherwise never return.
function Start-CampusService {
    param([string]$Name, [string]$Jar)
    $jarPath = Join-Path $root $Jar
    if (-not (Test-Path $jarPath)) { throw "missing build output: $jarPath (run: mvn -DskipTests clean package)" }
    $log = Join-Path $logs ($Name + '.log')
    $errLog = Join-Path $logs ($Name + '.err.log')
    Write-Host ('==> starting ' + $Name + ' (log: ' + $log + ')')
    $inner = '& ''' + $java + ''' ''@' + $argFile + ''' -jar ''' + $jarPath + ''' > ''' + $log + ''' 2> ''' + $errLog + ''''
    Start-Process -FilePath 'powershell.exe' `
        -ArgumentList @('-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', $inner) `
        -WorkingDirectory $root `
        -WindowStyle Hidden | Out-Null
}

if (-not $NoChain) {
    $chain = Join-Path $root 'chain-worker'
    if (Test-Path (Join-Path $chain 'server.mjs')) {
        Write-Host '==> starting chain-worker (EVM / LSTM)'
        # chain-worker reads the same secrets (LEDGER_KEY / AUDIT_KEY) from the environment
        $inner = 'node server.mjs > ''' + (Join-Path $logs 'chain.log') + ''' 2> ''' + (Join-Path $logs 'chain.err.log') + ''''
        Start-Process -FilePath 'powershell.exe' `
            -ArgumentList @('-NoProfile', '-NonInteractive', '-Command', $inner) `
            -WorkingDirectory $chain `
            -WindowStyle Hidden | Out-Null
    }
}

Start-CampusService -Name 'gateway' -Jar 'gateway\target\gateway-1.0.0.jar'
Start-Sleep -Seconds 8
Start-CampusService -Name 'data-service' -Jar 'data-service\target\data-service-1.0.0.jar'
Start-CampusService -Name 'audit-service' -Jar 'audit-service\target\audit-service-1.0.0.jar'
Start-Sleep -Seconds 12
Start-CampusService -Name 'business-service' -Jar 'business-service\target\business-service-1.0.0.jar'

Write-Host ''
Write-Host 'Started detached. Allow ~20s, then check https://localhost:8443/system'
Write-Host ('Logs: ' + $logs + '   Secrets: ' + $secretsFile + ' (injected as env vars and -D properties)')
