server:
  port: ${WEB_PORT:8443}
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: ${TLS_KEYSTORE}
    key-store-password: ${TLS_KEYSTORE_PASSWORD}
    key-store-type: ${TLS_KEYSTORE_TYPE:PKCS12}
  servlet:
    session:
      cookie:
        secure: true
rmi:
  tls-enabled: true
